{% set name = "polyglotdb" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34a3cf34f7b14cb670bd8caf7a988529f0c31536ed933c9a6b6d56d562bab6d5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - pgdb = polyglotdb.pgdb:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - openjdk =21
    - conch-sounds
    - influxdb
    - librosa
    - praatio
    - requests
    - tqdm
    - neo4j-python-driver
    - __unix                      # [unix]
    - __win                       # [win]
    - pywin32                     # [win]

test:
  imports:
    - polyglotdb
    - polyglotdb.acoustics
    - polyglotdb.acoustics.formants
    - polyglotdb.acoustics.pitch
    - polyglotdb.acoustics.vot
    - polyglotdb.client
    - polyglotdb.corpus
    - polyglotdb.databases
    - polyglotdb.io
    - polyglotdb.io.enrichment
    - polyglotdb.io.exporters
    - polyglotdb.io.importer
    - polyglotdb.io.inspect
    - polyglotdb.io.parsers
    - polyglotdb.io.types
    - polyglotdb.query
    - polyglotdb.query.annotations
    - polyglotdb.query.annotations.attributes
    - polyglotdb.query.base
    - polyglotdb.query.discourse
    - polyglotdb.query.lexicon
    - polyglotdb.query.metadata
    - polyglotdb.query.speaker
    - polyglotdb.syllabification
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MontrealCorpusTools/PolyglotDB
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PolyglotDB is a Python package for storing and querying large speech corpora.
  doc_url: https://polyglotdb.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/MontrealCorpusTools/PolyglotDB

extra:
  recipe-maintainers:
    - msonderegger
    - lxy2304
    - mmcauliffe
